import { ArrowRight, Eye, EyeOff, FileText, Loader2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { IconButton } from "./components/IconButton.jsx";
import { JsonEditor } from "./components/JsonEditor.jsx";
import { ResumePreview } from "./components/ResumePreview.jsx";
import { Toolbar } from "./components/Toolbar.jsx";
import { buildPrompt } from "./data/chatgptPrompt.js";
import { DEFAULT_DATA } from "./data/defaultResume.js";
import { FONTS } from "./data/fonts.js";
import { PRESETS } from "./data/presets.js";
import { downloadJson } from "./lib/download.js";
import { normalize, parseAndNormalize } from "./lib/normalize.js";
import { countResumeCharacters } from "./lib/resumeMetrics.js";
import {
	authenticateUser,
	clearLocalStorage,
	downloadResumeFromSupabase,
	registerUser,
	saveToLocalStorage,
	uploadResumeToSupabase,
} from "./lib/storage.js";

const DEBOUNCE_MS = 350;
const MARGIN_OPTIONS = [
	{ label: "Very Tight", value: 6 },
	{ label: "Tight", value: 8 },
	{ label: "Compact", value: 10 },
	{ label: "Jake", value: 12.7 },
];

function getResumeTitle(name) {
	const trimmedName = String(name ?? "").trim();
	const firstName = trimmedName.split(/\s+/).find(Boolean) ?? "Resume";
	return `${firstName} Resume`;
}

function setMetaTag(name, content) {
	let element = document.head.querySelector(`meta[name="${name}"]`);
	if (!element) {
		element = document.createElement("meta");
		element.setAttribute("name", name);
		document.head.appendChild(element);
	}
	element.setAttribute("content", content);
}

export default function App() {
	const defaultState = normalize(DEFAULT_DATA);
	const [jsonText, setJsonText] = useState(() =>
		JSON.stringify(defaultState.data, null, 2),
	);
	const [data, setData] = useState(() => defaultState.data);
	const [warnings, setWarnings] = useState([]);
	const [parseError, setParseError] = useState(null);
	const [isParsing, setIsParsing] = useState(false);
	const [pageMetrics, setPageMetrics] = useState(null);
	const [viewMode, setViewMode] = useState("split");
	const [isCompact, setIsCompact] = useState(
		() => window.matchMedia("(max-width: 900px)").matches,
	);
	const [currentUsername, setCurrentUsername] = useState(null);
	const [currentSyncKey, setCurrentSyncKey] = useState(null);
	const [usernameInput, setUsernameInput] = useState("");
	const [passwordInput, setPasswordInput] = useState("");
	const [showPassword, setShowPassword] = useState(false);
	const [authMode, setAuthMode] = useState("login");
	const [authError, setAuthError] = useState(null);
	const [isAuthenticating, setIsAuthenticating] = useState(false);
	const [syncMessage, setSyncMessage] = useState("");
	const [isUploading, setIsUploading] = useState(false);
	const [isDownloading, setIsDownloading] = useState(false);
	const debounceRef = useRef(null);
	const characterCount = countResumeCharacters(data);
	const selectedMargin = getSharedMargin(data.settings);
	const resumeTitle = getResumeTitle(data.header?.name);
	const activeView = isCompact && viewMode === "split" ? "preview" : viewMode;

	useEffect(() => {
		const media = window.matchMedia("(max-width: 900px)");
		const handleChange = (event) => setIsCompact(event.matches);
		media.addEventListener("change", handleChange);
		return () => media.removeEventListener("change", handleChange);
	}, []);

	useEffect(() => {
		document.title = resumeTitle;
		setMetaTag("author", "Varun Kedia");
		setMetaTag("generator", "Generated by PurpleResume");
		setMetaTag("application-name", "PurpleResume");
		setMetaTag("website", "https://purpleresume.vercel.app");
		setMetaTag(
			"description",
			"Generated by PurpleResume at purpleresume.vercel.app",
		);
	}, [resumeTitle]);

	useEffect(() => {
		if (!currentUsername) return undefined;

		if (debounceRef.current) clearTimeout(debounceRef.current);
		debounceRef.current = setTimeout(() => {
			const result = parseAndNormalize(jsonText);
			setParseError(result.parseError);
			setIsParsing(false);
			if (!result.parseError) {
				setData(result.data);
				setWarnings(result.warnings);
				saveToLocalStorage(currentUsername, result.data);
			}
		}, DEBOUNCE_MS);
		return () => clearTimeout(debounceRef.current);
	}, [currentUsername, jsonText]);

	const handleJsonChange = (text) => {
		if (text === jsonText) return;
		setJsonText(text);
		setIsParsing(true);
	};

	const updateSettings = (settingsPatch) => {
		const raw = parseJsonObject(jsonText);
		if (!raw) return;
		const settings = isObject(raw.settings) ? raw.settings : data.settings;
		const patch =
			typeof settingsPatch === "function"
				? settingsPatch(settings)
				: settingsPatch;
		const next = {
			...raw,
			settings: {
				...settings,
				...patch,
			},
		};
		handleJsonChange(JSON.stringify(next, null, 2));
	};

	const handleFontSizeStep = (step) => {
		updateSettings((settings) => {
			const currentSize = Number(
				settings.fontSize ?? data.settings.fontSize,
			);
			const size = Number.isFinite(currentSize)
				? currentSize
				: data.settings.fontSize;
			return { fontSize: Math.max(6, Math.min(30, size + step)) };
		});
	};

	const handleReset = () => {
		const confirmed = window.confirm(
			"Reset the resume to the starter template? This clears your saved draft.",
		);
		if (!confirmed) return;

		const result = normalize(DEFAULT_DATA);
		clearLocalStorage(currentUsername);
		setJsonText(JSON.stringify(DEFAULT_DATA, null, 2));
		setData(result.data);
		setWarnings(result.warnings);
		setParseError(null);
		setIsParsing(false);
		setPageMetrics(null);
	};

	const handlePasswordSubmit = async (event) => {
		event.preventDefault();
		if (isAuthenticating) return;

		const trimmedUsername = String(usernameInput ?? "").trim();
		if (!trimmedUsername) {
			setAuthError("Enter a username.");
			return;
		}
		if (!passwordInput) {
			setAuthError("Enter a password.");
			return;
		}

		setIsAuthenticating(true);
		setAuthError(null);
		try {
			const result =
				authMode === "login"
					? await authenticateUser(trimmedUsername, passwordInput)
					: await registerUser(trimmedUsername, passwordInput);

			if (!result.ok) {
				setAuthError(result.error);
				return;
			}

			loadResumeForUser(result.user);
			setCurrentSyncKey(result.user.syncKey ?? null);
			setSyncMessage("");
			setUsernameInput("");
			setPasswordInput("");
			setShowPassword(false);
			setAuthMode("login");
		} catch (error) {
			setAuthError(
				error instanceof Error
					? error.message
					: "Unable to sign in. Please try again.",
			);
		} finally {
			setIsAuthenticating(false);
		}
	};

	function loadResumeForUser(user) {
		const result = normalize(user.resumeData ?? DEFAULT_DATA);
		setCurrentUsername(user.username);
		setJsonText(JSON.stringify(result.data, null, 2));
		setData(result.data);
		setWarnings(result.warnings);
		setParseError(null);
		setIsParsing(false);
		setPageMetrics(null);
	}

	const handleSignOut = () => {
		setCurrentUsername(null);
		setCurrentSyncKey(null);
		setUsernameInput("");
		setPasswordInput("");
		setShowPassword(false);
		setAuthMode("login");
		setAuthError(null);
		setJsonText(JSON.stringify(defaultState.data, null, 2));
		setData(defaultState.data);
		setWarnings([]);
		setParseError(null);
		setIsParsing(false);
		setPageMetrics(null);
		setSyncMessage("");
	};

	const handleUploadToCloud = async () => {
		if (!currentUsername || !currentSyncKey) {
			setSyncMessage("Sync failed: please sign in again.");
			return;
		}

		if (parseError) {
			setSyncMessage("Fix JSON errors before uploading.");
			return;
		}

		setIsUploading(true);
		setSyncMessage("Uploading to Supabase...");
		const result = await uploadResumeToSupabase({
			username: currentUsername,
			syncKey: currentSyncKey,
			data,
		});
		setIsUploading(false);

		if (!result.ok) {
			setSyncMessage(`Upload failed: ${result.error}`);
			return;
		}

		setSyncMessage(
			result.updatedAt
				? `Uploaded to Supabase at ${new Date(result.updatedAt).toLocaleString()}.`
				: "Uploaded to Supabase.",
		);
	};

	const handleDownloadFromCloud = async () => {
		if (!currentUsername || !currentSyncKey) {
			setSyncMessage("Sync failed: please sign in again.");
			return;
		}

		if (!window.confirm("Replace your local draft with the cloud copy?"))
			return;

		setIsDownloading(true);
		setSyncMessage("Downloading from Supabase...");
		const result = await downloadResumeFromSupabase({
			username: currentUsername,
			syncKey: currentSyncKey,
		});
		setIsDownloading(false);

		if (!result.ok) {
			setSyncMessage(`Download failed: ${result.error}`);
			return;
		}

		if (!result.data) {
			setSyncMessage("No cloud resume found yet for this account.");
			return;
		}

		const normalized = normalize(result.data);
		saveToLocalStorage(currentUsername, normalized.data);
		setJsonText(JSON.stringify(normalized.data, null, 2));
		setData(normalized.data);
		setWarnings(normalized.warnings);
		setParseError(null);
		setIsParsing(false);
		setSyncMessage(
			result.updatedAt
				? `Downloaded cloud resume from ${new Date(result.updatedAt).toLocaleString()}.`
				: "Downloaded cloud resume.",
		);
	};

	if (!currentUsername) {
		const isLogin = authMode === "login";

		return (
			<div className="auth-shell">
				<div className="auth-card">
					<div className="brand-lockup auth-brand">
						<span className="brand-mark">
							<FileText
								size={19}
								strokeWidth={1.7}
								aria-hidden="true"
							/>
						</span>
						<span>
							Purple<span className="brand-wordmark">Resume</span>
						</span>
					</div>
					<h1 className="auth-title">Your resume workspace</h1>
					<div
						className="auth-actions"
						role="group"
						aria-label="Account access"
					>
						<button
							aria-pressed={isLogin}
							className={
								isLogin ? "auth-submit" : "auth-secondary"
							}
							disabled={isAuthenticating}
							onClick={() => {
								if (isLogin) return;
								setAuthMode("login");
								setAuthError(null);
								setPasswordInput("");
								setShowPassword(false);
							}}
							type="button"
						>
							Sign in
						</button>
						<button
							aria-pressed={!isLogin}
							className={
								isLogin ? "auth-secondary" : "auth-submit"
							}
							disabled={isAuthenticating}
							onClick={() => {
								if (!isLogin) return;
								setAuthMode("signup");
								setAuthError(null);
								setPasswordInput("");
								setShowPassword(false);
							}}
							type="button"
						>
							Create account
						</button>
					</div>
					<form
						className="auth-form"
						onSubmit={handlePasswordSubmit}
						aria-busy={isAuthenticating}
					>
						<label className="auth-field">
							<span>Username</span>
							<input
								autoCapitalize="none"
								autoComplete="username"
								className="auth-input"
								disabled={isAuthenticating}
								name="username"
								onChange={(event) => {
									setUsernameInput(event.target.value);
									setAuthError(null);
								}}
								placeholder="your-name"
								required
								spellCheck={false}
								value={usernameInput}
							/>
						</label>
						<div className="auth-field">
							<label htmlFor="account-password">
								{isLogin ? "Password" : "Create password"}
							</label>
							<div className="password-input-wrap">
								<input
									id="account-password"
									autoComplete={
										isLogin
											? "current-password"
											: "new-password"
									}
									className="auth-input"
									disabled={isAuthenticating}
									name="password"
									onChange={(event) => {
										setPasswordInput(event.target.value);
										setAuthError(null);
									}}
									placeholder={
										isLogin
											? "Enter password"
											: "Create password"
									}
									required
									type={showPassword ? "text" : "password"}
									value={passwordInput}
								/>
								<IconButton
									icon={showPassword ? EyeOff : Eye}
									label={
										showPassword
											? "Hide password"
											: "Show password"
									}
									onClick={() =>
										setShowPassword(!showPassword)
									}
									disabled={isAuthenticating}
									align="end"
								/>
							</div>
						</div>
						{authError ? (
							<p className="auth-error" role="alert">
								{authError}
							</p>
						) : null}
						<button
							className="auth-submit"
							disabled={isAuthenticating}
							type="submit"
						>
							{isAuthenticating
								? isLogin
									? "Signing in..."
									: "Creating account..."
								: isLogin
									? "Sign in"
									: "Create account"}
							{isAuthenticating ? (
								<Loader2
									size={16}
									className="is-spinning"
									aria-hidden="true"
								/>
							) : (
								<ArrowRight size={16} aria-hidden="true" />
							)}
						</button>
					</form>
				</div>
			</div>
		);
	}

	return (
		<div className="app-shell">
			<Toolbar
				currentUsername={currentUsername}
				resumeTitle={resumeTitle}
				viewMode={activeView}
				onViewChange={setViewMode}
				fontSize={data.settings.fontSize}
				onFontSizeStep={handleFontSizeStep}
				isParsing={isParsing}
				hasError={Boolean(parseError)}
				syncMessage={syncMessage}
				syncBusy={isUploading || isDownloading}
				onDismissMessage={() => setSyncMessage("")}
				presets={PRESETS}
				selectedPreset={data.settings.preset}
				onPresetChange={(preset) => updateSettings({ preset })}
				fonts={FONTS}
				selectedFont={data.settings.fontFamily}
				onFontChange={(fontFamily) => updateSettings({ fontFamily })}
				marginOptions={MARGIN_OPTIONS}
				selectedMargin={selectedMargin}
				onMarginChange={(margin) =>
					updateSettings({
						marginTop: margin,
						marginBottom: margin,
						marginLeft: margin,
						marginRight: margin,
					})
				}
				onExportPdf={() => {
					document.title = resumeTitle;
					setMetaTag("author", "Varun Kedia");
					setMetaTag("generator", "Generated by PurpleResume");
					setMetaTag("website", "https://purpleresume.vercel.app");
					window.print();
				}}
				onExportJson={() => downloadJson(data, "resume.json")}
				onDownloadStarter={() =>
					downloadJson(DEFAULT_DATA, "purpleresume-starter.json")
				}
				onCopyPrompt={() =>
					navigator.clipboard.writeText(buildPrompt(jsonText))
				}
				onImportFile={handleJsonChange}
				onUploadSync={handleUploadToCloud}
				onDownloadSync={handleDownloadFromCloud}
				onReset={handleReset}
				onSignOut={handleSignOut}
			/>
			<main
				className={`app-body view-${activeView}`}
				aria-label="Resume workspace"
			>
				<section
					className="editor-pane no-print"
					aria-label="JSON source"
				>
					<JsonEditor
						text={jsonText}
						onChange={handleJsonChange}
						warnings={warnings}
						parseError={parseError}
						resumeMetrics={{
							characterCount,
							page: pageMetrics,
						}}
					/>
				</section>
				<ResumePreview
					data={data}
					onMetricsChange={setPageMetrics}
					metrics={pageMetrics}
					hasError={Boolean(parseError)}
				/>
			</main>
		</div>
	);
}

function parseJsonObject(text) {
	try {
		const parsed = JSON.parse(stripCodeFence(text));
		return isObject(parsed) ? parsed : null;
	} catch {
		return null;
	}
}

function stripCodeFence(text) {
	const trimmed = String(text ?? "").trim();
	const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
	return fenced ? fenced[1] : trimmed;
}

function isObject(value) {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}

function getSharedMargin(settings) {
	const margins = [
		settings.marginTop,
		settings.marginBottom,
		settings.marginLeft,
		settings.marginRight,
	];
	const [first] = margins;
	return margins.every((margin) => margin === first) ? first : "custom";
}
