import { useEffect, useRef, useState } from "react";
import { JsonEditor } from "./components/JsonEditor.jsx";
import { ResumePreview } from "./components/ResumePreview.jsx";
import { Toolbar } from "./components/Toolbar.jsx";
import { buildPrompt } from "./data/chatgptPrompt.js";
import { DEFAULT_DATA } from "./data/defaultResume.js";
import { FONTS } from "./data/fonts.js";
import { PRESETS } from "./data/presets.js";
import { downloadJson } from "./lib/download.js";
import { normalize, parseAndNormalize } from "./lib/normalize.js";
import { countResumeCharacters } from "./lib/resumeMetrics.js";
import {
	clearLocalStorage,
	loadFromLocalStorage,
	saveToLocalStorage,
} from "./lib/storage.js";

const DEBOUNCE_MS = 350;
const SITE_URL = "https://purplevarun.github.io/resume";
const MARGIN_OPTIONS = [
	{ label: "Very Tight", value: 6 },
	{ label: "Tight", value: 8 },
	{ label: "Compact", value: 10 },
	{ label: "Jake", value: 12.7 },
];

function getResumeTitle(name) {
	const trimmedName = String(name ?? "").trim();
	const firstName = trimmedName.split(/\s+/).find(Boolean) ?? "Resume";
	return `${firstName} Resume`;
}

function setMetaTag(name, content) {
	let element = document.head.querySelector(`meta[name="${name}"]`);
	if (!element) {
		element = document.createElement("meta");
		element.setAttribute("name", name);
		document.head.appendChild(element);
	}
	element.setAttribute("content", content);
}

export default function App() {
	const [initialState] = useState(() =>
		normalize(loadFromLocalStorage() ?? DEFAULT_DATA),
	);
	const [jsonText, setJsonText] = useState(() =>
		JSON.stringify(initialState.data, null, 2),
	);
	const [data, setData] = useState(initialState.data);
	const [warnings, setWarnings] = useState(initialState.warnings);
	const [parseError, setParseError] = useState(null);
	const [isParsing, setIsParsing] = useState(false);
	const [pageMetrics, setPageMetrics] = useState(null);
	const [viewMode, setViewMode] = useState("split");
	const [isCompact, setIsCompact] = useState(
		() => window.matchMedia("(max-width: 900px)").matches,
	);
	const debounceRef = useRef(null);
	const characterCount = countResumeCharacters(data);
	const selectedMargin = getSharedMargin(data.settings);
	const resumeTitle = getResumeTitle(data.header?.name);
	const activeView = isCompact && viewMode === "split" ? "preview" : viewMode;

	useEffect(() => {
		const media = window.matchMedia("(max-width: 900px)");
		const handleChange = (event) => setIsCompact(event.matches);
		media.addEventListener("change", handleChange);
		return () => media.removeEventListener("change", handleChange);
	}, []);

	useEffect(() => {
		document.title = resumeTitle;
		setMetaTag("author", "Varun Kedia");
		setMetaTag("generator", "Generated by PurpleResume");
		setMetaTag("application-name", "PurpleResume");
		setMetaTag("website", SITE_URL);
		setMetaTag("description", `Generated by PurpleResume at ${SITE_URL}`);
	}, [resumeTitle]);

	useEffect(() => {
		if (debounceRef.current) clearTimeout(debounceRef.current);
		debounceRef.current = setTimeout(() => {
			const result = parseAndNormalize(jsonText);
			setParseError(result.parseError);
			setIsParsing(false);
			if (!result.parseError) {
				setData(result.data);
				setWarnings(result.warnings);
				saveToLocalStorage(result.data);
			}
		}, DEBOUNCE_MS);
		return () => clearTimeout(debounceRef.current);
	}, [jsonText]);

	const handleJsonChange = (text) => {
		if (text === jsonText) return;
		setJsonText(text);
		setIsParsing(true);
	};

	const updateSettings = (settingsPatch) => {
		const raw = parseJsonObject(jsonText);
		if (!raw) return;
		const settings = isObject(raw.settings) ? raw.settings : data.settings;
		const patch =
			typeof settingsPatch === "function"
				? settingsPatch(settings)
				: settingsPatch;
		const next = {
			...raw,
			settings: {
				...settings,
				...patch,
			},
		};
		handleJsonChange(JSON.stringify(next, null, 2));
	};

	const handleFontSizeStep = (step) => {
		updateSettings((settings) => {
			const currentSize = Number(
				settings.fontSize ?? data.settings.fontSize,
			);
			const size = Number.isFinite(currentSize)
				? currentSize
				: data.settings.fontSize;
			return { fontSize: Math.max(6, Math.min(30, size + step)) };
		});
	};

	const handleReset = () => {
		const confirmed = window.confirm(
			"Reset the resume to the starter template? This clears your saved draft.",
		);
		if (!confirmed) return;

		const result = normalize(DEFAULT_DATA);
		clearLocalStorage();
		setJsonText(JSON.stringify(DEFAULT_DATA, null, 2));
		setData(result.data);
		setWarnings(result.warnings);
		setParseError(null);
		setIsParsing(false);
		setPageMetrics(null);
	};

	return (
		<div className="app-shell">
			<Toolbar
				resumeTitle={resumeTitle}
				viewMode={activeView}
				onViewChange={setViewMode}
				fontSize={data.settings.fontSize}
				onFontSizeStep={handleFontSizeStep}
				isParsing={isParsing}
				hasError={Boolean(parseError)}
				presets={PRESETS}
				selectedPreset={data.settings.preset}
				onPresetChange={(preset) => updateSettings({ preset })}
				fonts={FONTS}
				selectedFont={data.settings.fontFamily}
				onFontChange={(fontFamily) => updateSettings({ fontFamily })}
				marginOptions={MARGIN_OPTIONS}
				selectedMargin={selectedMargin}
				onMarginChange={(margin) =>
					updateSettings({
						marginTop: margin,
						marginBottom: margin,
						marginLeft: margin,
						marginRight: margin,
					})
				}
				onExportPdf={() => {
					document.title = resumeTitle;
					setMetaTag("author", "Varun Kedia");
					setMetaTag("generator", "Generated by PurpleResume");
					setMetaTag("website", SITE_URL);
					window.print();
				}}
				onExportJson={() => downloadJson(data, "resume.json")}
				onCopyPrompt={() =>
					navigator.clipboard.writeText(buildPrompt(jsonText))
				}
				onReset={handleReset}
			/>
			<main
				className={`app-body view-${activeView}`}
				aria-label="Resume workspace"
			>
				<section
					className="editor-pane no-print"
					aria-label="JSON source"
				>
					<JsonEditor
						text={jsonText}
						onChange={handleJsonChange}
						warnings={warnings}
						parseError={parseError}
						resumeMetrics={{
							characterCount,
							page: pageMetrics,
						}}
					/>
				</section>
				<ResumePreview
					data={data}
					onMetricsChange={setPageMetrics}
					metrics={pageMetrics}
					hasError={Boolean(parseError)}
				/>
			</main>
		</div>
	);
}

function parseJsonObject(text) {
	try {
		const parsed = JSON.parse(stripCodeFence(text));
		return isObject(parsed) ? parsed : null;
	} catch {
		return null;
	}
}

function stripCodeFence(text) {
	const trimmed = String(text ?? "").trim();
	const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
	return fenced ? fenced[1] : trimmed;
}

function isObject(value) {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}

function getSharedMargin(settings) {
	const margins = [
		settings.marginTop,
		settings.marginBottom,
		settings.marginLeft,
		settings.marginRight,
	];
	const [first] = margins;
	return margins.every((margin) => margin === first) ? first : "custom";
}
